branches:
  only:
    - master

sudo: required
services:
  - docker
language: node_js
node_js:
  - 6.7.0
before_script:
  - npm install -g grunt-cli
script:
  - grunt build
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/publish-release.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/publish-docker.sh; fi'

