DOCKER_EMAIL:
  secure: ak/W6mVkY6u3d6wS92A1UGWchEjbfU7GsmxykIxeS48aXTaHF52COxrmuadeTOx0unR/GL9/gBKcph9g/bACf2vbz8bhEpylZv/p4ROTuceWL4ovyOIF/0vjr6k7Kl4rZVQbesS0CYhwvtmISarOyLG/3+3E7SDY3POYLiqQM7ZeLMhIv2+1kKaPg4CFCGYKtY4Kmr0mATPhPKH0rls44iKh/dpilFSOcrKDeHxZFykVFidoTyoAYawuPVXactG1pcRjR71nNsYq23bRjcVvlhz83rjMHA1UpxfRzviPTV2BbQzO3AOzoHZ10Lo19QUDmuQVTo+TpqS54pusdO3+yj/9zmVzUMelMhNrfZucr3LscBd03O67Il1oefNYG9aTKA9XB9XQa1h7K1MhWignTQzsqKvJwZ786oDw1/xCImlwlSWci3CR4P3uqraXL8ZPrCxTqINyrnwE7KBE8NKM7pOvXjeQZR344/9+Cl7bh+0yFET7+F8s82B3/yYNewp2BBPVEuBfaycXAjBAbXLDlGX0XlazRHo5CMCsI2fr43vbCmL3jR7VnjlxgDSb8oN3uVI92kByTTeksE3QwPKKInQjRKuLrxYuHvpg58a+M9c68pS6N+y/bvYXKrlapvS33A0iGkSlQHyKgJ1x29zDwNyJfwsV69MNlP9wEczJp4M=
DOCKER_USER:
  secure: X8sxfzyrZY/U3f8/Xq5VbeKrL61VcFV0RqhWp/T2if72jaJT7ubYNEVy+869NJGSC9a/0YkQkpZ1SrmmVxBz1+UtAuuIS85Hhgq1vHQg32+96EbdJH5KKPwi3YDGeSewDXZvOGDXJRqkONCyoGEBT2Y5oIiwBk0DXXEQiRPZZxQNR/iZXjJqSIFgt7AI2nSGkN22Ai/pipO+8g9Ke7Dq9xGAQOvhMDWiGiIj8EQTsop8TO9++Z6ErDFZqoz8ZBkW+Y0RzdegVsfUGWz+oU5TjNl3sXsG3HM5L7FU0zU2vNVWs74qoJGycb0U/pFKjFlRe1O2isYD9tc9Lx4ZzxX7ulZJ5BMdBTSq4u50akK5Q6CUAteP1CmAsodFzzkuI4EmcUFsBr17pblHFVOOAs5y3p216qVQpCGRU54NTnULrxdPzOwsZr68BacD8RF7+WS21czpWAaeM/cgtop9BK558y7HA1pIrDKWZQyNOn8C9Y/nCjHs9lp/qhXBrmF1KNgFdeiFpynnnxgenM1sKmA4695BOODTGbUYbAQt+V6C6s2i/xCX4Nv9e71jv7CXA5TlHQpL6BsM9YWEMdQuhuzd5YTQQf3qOwiWtR6Kcp+iqmQbPwYDh50+CbpUlWmd0ctdSlmAXDK6y0ZdIbbIHjyxS5L0BYbg1RgMJxWjeRpM77E=
DOCKER_PASS:
  secure: jQMbcPFMhm8AbLyMIUskYgs4Uo9ZMdwgJjpN+aBSWYB8LjSN07Qw9CiIbaOXE+nRshpPumH++U5hHlBRfy8d8/kU/5m/aAn8akDeH9pwSgHSIRcsKnjvRq5ZemLWvYHmWCoCjJfaBbHpE/kpNiZeynQHXmUwNBexB0dzP72pKzhK5ivj0gLt/HRyWDnvIkHKk7T8gduKM3ENmuMNZFFwKKjpFiioBwgEeALLnQJbSU2bxMdWU+QzRv9Zp330j5MSwCfIRoXxs7QD07FgpITG9Y9KJtaZEotRMGYUqhask2zV1/0S2U0qLpHaWR1ms1z4dok1HFynsiMBxn7KCwzsYhkjFoGu8nRzWgM3Ws4gAQ4u0Qkia3X1Sdd0dxzYTZSD2+qA7V4dMHyiWugA5KqmF2yYRzDX23JAuIrM2GyP3n1PIBzdEa7ULk1ib1uZGflsNSZU3Rc3keJQwPYTJlF6+2ZqlYS/V3RRM8NhViXvN70PR0MNBuARgJz/pJG/oIfbO/4mvw80A0AY85fTLoeSDpIEF/YVz4N0EifjNc8j3bEPqvmrd4OwHlg6ShpTEwvDochF44/QYfre/a7CMbFz9Dz1W1Gs4ypeFljDW9rv1ziZNKxWYPELxVzJECfToOJ/SRA70zFpSXrsFeUIUOZkUeGZGB7O3/uPYLrb/kHl1w0=

services:
- docker
language: node_js
node_js:
- 6.3.1
before_script:
- npm install -g grunt-cli
script:
- grunt build
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=DevOpsPlayground/directory-react-nodejs
- docker build -f Dockerfile -t sameetn/directory-react-nodejs:latest .
- docker push sameetn/directory-react-nodejs:latest
