sudo: required

services:
  - docker
language: node_js
node_js:
  - 6.3.1
before_script:
  - npm install -g grunt-cli
script:
  - grunt build
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t sameetn/directory-react-nodejs:latest .
  - docker push sameetn/directory-react-nodejs:latest
