branches:
  only:
    - master
sudo: required
services:
  - docker
language: node_js
node_js:
  - 6.7.0
before_script:
  - npm install -g grunt-cli
script:
  - grunt buil
after_script:
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - export CURR_VER=`cat package.json | grep version | tr -s " " ":" | cut -d "\"" -f4`
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/publish-release.sh; fi'
  # - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/publish-docker.sh; fi'

